### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by TwistTheNeil** [TwistTheNeil/brick#14]
~ ⍉ ➜ /home/neil/other/brick/brick forecast now | grep -v config > /tmp/phl-weather
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
brick/providers.OpenWeatherMap.CurrentWeather(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/neil/other/brick/providers/OpenWeatherMap.go:84 +0x300
brick/cmd.glob..func2(0xcda7e0, 0xcffbc0, 0x0, 0x0)
	/home/neil/other/brick/cmd/forecast_now.go:16 +0x5b
github.com/spf13/cobra.(*Command).execute(0xcda7e0, 0xcffbc0, 0x0, 0x0, 0xcda7e0, 0xcffbc0)
	/home/neil/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xcdaa80, 0xce2da0, 0x92b822, 0x1b)
	/home/neil/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/neil/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
brick/cmd.Execute()
	/home/neil/other/brick/cmd/root.go:24 +0x31
main.main()
	/home/neil/other/brick/main.go:10 +0x27

**Comment by TwistTheNeil** [comment]
7b0078343aa3b76235c63194895bc299d9594cfb
